openapi: 3.1.0
info:
  title: Commerce Layer addresses checkout_com_payments API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: checkout_com_payments
  description: resource type
paths:
  /checkout_com_gateways/{checkoutComGatewayId}/checkout_com_payments:
    get:
      operationId: GET/checkoutComGatewayId/checkout_com_payments
      summary: Retrieve the checkout com payments associated to the checkout.com gateway
      description: Retrieve the checkout com payments associated to the checkout.com gateway
      tags:
      - checkout_com_payments
      parameters:
      - name: checkoutComGatewayId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The checkout_com_payments associated to the checkout.com gateway
  /checkout_com_payments:
    get:
      operationId: GET/checkout_com_payments
      summary: List all checkout.com payments
      description: List all checkout.com payments
      tags:
      - checkout_com_payments
      responses:
        '200':
          description: A list of checkout.com payment objects
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/checkoutComPaymentResponseList'
    post:
      operationId: POST/checkout_com_payments
      summary: Create a checkout.com payment
      description: Create a checkout.com payment
      tags:
      - checkout_com_payments
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/checkoutComPaymentCreate'
      responses:
        '201':
          description: The created checkout.com payment object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/checkoutComPaymentResponse'
  /checkout_com_payments/{checkoutComPaymentId}:
    get:
      operationId: GET/checkout_com_payments/checkoutComPaymentId
      summary: Retrieve a checkout.com payment
      description: Retrieve a checkout.com payment
      tags:
      - checkout_com_payments
      parameters:
      - name: checkoutComPaymentId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The checkout.com payment object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/checkoutComPaymentResponse'
    patch:
      operationId: PATCH/checkout_com_payments/checkoutComPaymentId
      summary: Update a checkout.com payment
      description: Update a checkout.com payment
      tags:
      - checkout_com_payments
      parameters:
      - name: checkoutComPaymentId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/checkoutComPaymentUpdate'
      responses:
        '200':
          description: The updated checkout.com payment object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/checkoutComPaymentResponse'
    delete:
      operationId: DELETE/checkout_com_payments/checkoutComPaymentId
      summary: Delete a checkout.com payment
      description: Delete a checkout.com payment
      tags:
      - checkout_com_payments
      parameters:
      - name: checkoutComPaymentId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '204':
          description: No content
components:
  schemas:
    checkoutComPaymentUpdate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - checkout_com_payments
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            attributes:
              type: object
              properties:
                token:
                  type: string
                  description: The Checkout.com payment or digital wallet token.
                  example: tok_4gzeau5o2uqubbk6fufs3m7p54
                  nullable: false
                _details:
                  type: boolean
                  description: Send this attribute if you want to send additional details the payment request (i.e. upon 3DS check).
                  example: true
                  nullable: false
                _refresh:
                  type: boolean
                  description: Send this attribute if you want to refresh all the pending transactions, can be used as webhooks fallback logic.
                  example: true
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties:
                order:
                  required:
                  - data
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - orders
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
    checkoutComPaymentResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            type:
              type: string
              description: The resource's type
              enum:
              - checkout_com_payments
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/checkoutComPayment/properties/data/properties/attributes'
            relationships:
              type: object
              properties:
                order:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - order
                        id:
                          type: string
                          description: The resource ID
                payment_gateway:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - payment_gateway
                        id:
                          type: string
                          description: The resource ID
                event_stores:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: The resource ID
    checkoutComPaymentResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/checkoutComPaymentResponse/properties/data'
    checkoutComPaymentCreate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - checkout_com_payments
            attributes:
              type: object
              properties:
                token:
                  type: string
                  description: The Checkout.com payment or digital wallet token.
                  example: tok_4gzeau5o2uqubbk6fufs3m7p54
                success_url:
                  type: string
                  description: The URL to redirect your customer upon 3DS succeeded authentication.
                  example: http://commercelayer.dev/checkout_com/success
                failure_url:
                  type: string
                  description: The URL to redirect your customer upon 3DS failed authentication.
                  example: http://commercelayer.dev/checkout_com/failure
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
              required:
              - token
              - success_url
              - failure_url
            relationships:
              type: object
              properties:
                order:
                  required:
                  - data
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - orders
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
              required:
              - order
    checkoutComPayment:
      properties:
        data:
          properties:
            attributes:
              type: object
              properties:
                public_key:
                  type: string
                  description: The Checkout.com publishable API key.
                  example: pk_test_xxxx-yyyy-zzzz
                  nullable: true
                token:
                  type: string
                  description: The Checkout.com payment or digital wallet token.
                  example: tok_4gzeau5o2uqubbk6fufs3m7p54
                  nullable: false
                payment_session:
                  type: object
                  description: The session object which initializes payment.
                  example:
                    id: ps_xxxx_yyyy_zzzz
                    payment_session_secret: pss_xxxx_yyy_zzzz
                    payment_session_token: xxxxx_yyyyy_zzzzz
                    _links:
                      self:
                        href: https://api.sandbox.checkout.com/payment-sessions/ps_xxxx_yyyy_zzzz
                  nullable: false
                success_url:
                  type: string
                  description: The URL to redirect your customer upon 3DS succeeded authentication.
                  example: http://commercelayer.dev/checkout_com/success
                  nullable: false
                failure_url:
                  type: string
                  description: The URL to redirect your customer upon 3DS failed authentication.
                  example: http://commercelayer.dev/checkout_com/failure
                  nullable: false
                source_id:
                  type: string
                  description: The payment source identifier that can be used for subsequent payments.
                  example: src_nwd3m4in3hkuddfpjsaevunhdy
                  nullable: true
                customer_token:
                  type: string
                  description: The customer's unique identifier. This can be passed as a source when making a payment.
                  example: cus_udst2tfldj6upmye2reztkmm4i
                  nullable: true
                redirect_uri:
                  type: string
                  description: The URI that the customer should be redirected to in order to complete the payment.
                  example: https://api.checkout.com/3ds/pay_mbabizu24mvu3mela5njyhpit4
                  nullable: true
                payment_response:
                  type: object
                  description: The Checkout.com payment response, used to fetch internal data.
                  example:
                    foo: bar
                  nullable: true
                mismatched_amounts:
                  type: boolean
                  description: Indicates if the order current amount differs form the one of the associated authorization.
                  example: false
                  nullable: true
                payment_instrument:
                  type: object
                  description: Information about the payment instrument used in the transaction.
                  example:
                    issuer: cl bank
                    card_type: visa
                  nullable: true
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
